# Generated by Django 5.2.9 on 2025-12-07

import cookbook.models
import django.db.models.deletion
import django_prometheus.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0234_alter_shoppinglist_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='recipes/')),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cookbook.recipe')),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
                'indexes': [models.Index(fields=['recipe', 'is_primary'], name='cookbook_re_recipe__a1b2c3_idx')],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('recipe_image'), models.Model, cookbook.models.PermissionModelMixin),
        ),
    ]
