# Generated by Django 5.2.9 on 2025-12-08
# Data migration to copy legacy Recipe.image to RecipeImage model
#
# Runtime: O(n) where n = recipes with legacy image and no gallery entries.
#          Typically fast (<1s). Safe to run multiple times (idempotent via filter).
#
# Safety: Only creates RecipeImage entries for recipes with NO existing gallery items.
#         For recipes that have BOTH legacy image AND gallery items, see migration 0238.
from django.db import migrations, transaction


def migrate_legacy_images(apps, schema_editor):
    """
    Copy all existing Recipe.image values to the RecipeImage model.
    This ensures existing recipes with images continue to work with
    the new multiple-image system.

    Uses atomic transaction to ensure data consistency - if migration
    fails partway through, all changes are rolled back.
    """
    Recipe = apps.get_model('cookbook', 'Recipe')
    RecipeImage = apps.get_model('cookbook', 'RecipeImage')

    # Find all recipes that have an image but no RecipeImage entries
    recipes_with_legacy_image = Recipe.objects.exclude(
        image=''
    ).exclude(
        image__isnull=True
    ).filter(
        images__isnull=True  # No RecipeImage entries yet
    ).distinct()

    created_count = 0
    with transaction.atomic():
        for recipe in recipes_with_legacy_image:
            # Create a RecipeImage entry for the legacy image
            RecipeImage.objects.create(
                recipe=recipe,
                image=recipe.image,  # Copy the image path
                is_primary=True,
                sort_order=0,
                created_by=recipe.created_by
            )
            created_count += 1

    if created_count > 0:
        print(f"\n  Migrated {created_count} legacy images to RecipeImage model")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration: Delete RecipeImage entries that were created from legacy images.
    Note: This only removes the RecipeImage entries, it does not delete the actual
    image files as they are still referenced by Recipe.image.
    """
    Recipe = apps.get_model('cookbook', 'Recipe')
    RecipeImage = apps.get_model('cookbook', 'RecipeImage')

    # Find RecipeImage entries where the image path matches Recipe.image
    # These are the ones we created during forward migration
    deleted_count = 0
    for recipe in Recipe.objects.exclude(image='').exclude(image__isnull=True):
        # Delete RecipeImage entries that match the legacy image path
        deleted = RecipeImage.objects.filter(
            recipe=recipe,
            image=recipe.image
        ).delete()[0]
        deleted_count += deleted

    if deleted_count > 0:
        print(f"\n  Removed {deleted_count} RecipeImage entries during reverse migration")


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0235_recipeimage'),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_images, reverse_migration),
    ]
