/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecipeImageItem } from './RecipeImageItem';
import {
    RecipeImageItemFromJSON,
    RecipeImageItemFromJSONTyped,
    RecipeImageItemToJSON,
} from './RecipeImageItem';

/**
 * 
 * @export
 * @interface PaginatedRecipeImageItemList
 */
export interface PaginatedRecipeImageItemList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedRecipeImageItemList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedRecipeImageItemList
     */
    next?: string;
    /**
     * 
     * @type {string}
     * @memberof PaginatedRecipeImageItemList
     */
    previous?: string;
    /**
     * 
     * @type {Array<RecipeImageItem>}
     * @memberof PaginatedRecipeImageItemList
     */
    results: Array<RecipeImageItem>;
    /**
     * 
     * @type {Date}
     * @memberof PaginatedRecipeImageItemList
     */
    timestamp?: Date;
}

/**
 * Check if a given object implements the PaginatedRecipeImageItemList interface.
 */
export function instanceOfPaginatedRecipeImageItemList(value: object): value is PaginatedRecipeImageItemList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedRecipeImageItemListFromJSON(json: any): PaginatedRecipeImageItemList {
    return PaginatedRecipeImageItemListFromJSONTyped(json, false);
}

export function PaginatedRecipeImageItemListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedRecipeImageItemList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(RecipeImageItemFromJSON)),
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
    };
}

export function PaginatedRecipeImageItemListToJSON(value?: PaginatedRecipeImageItemList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(RecipeImageItemToJSON)),
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
    };
}

