/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * Serializer for individual RecipeImage objects (multiple images per recipe).
 * @export
 * @interface PatchedRecipeImageItem
 */
export interface PatchedRecipeImageItem {
    /**
     * 
     * @type {number}
     * @memberof PatchedRecipeImageItem
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedRecipeImageItem
     */
    recipe?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedRecipeImageItem
     */
    image?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedRecipeImageItem
     */
    imageUrl?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedRecipeImageItem
     */
    isPrimary?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PatchedRecipeImageItem
     */
    sortOrder?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedRecipeImageItem
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedRecipeImageItem
     */
    readonly updatedAt?: Date;
    /**
     * 
     * @type {User}
     * @memberof PatchedRecipeImageItem
     */
    readonly createdBy?: User;
}

/**
 * Check if a given object implements the PatchedRecipeImageItem interface.
 */
export function instanceOfPatchedRecipeImageItem(value: object): value is PatchedRecipeImageItem {
    return true;
}

export function PatchedRecipeImageItemFromJSON(json: any): PatchedRecipeImageItem {
    return PatchedRecipeImageItemFromJSONTyped(json, false);
}

export function PatchedRecipeImageItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedRecipeImageItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'recipe': json['recipe'] == null ? undefined : json['recipe'],
        'image': json['image'] == null ? undefined : json['image'],
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
        'isPrimary': json['is_primary'] == null ? undefined : json['is_primary'],
        'sortOrder': json['sort_order'] == null ? undefined : json['sort_order'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'createdBy': json['created_by'] == null ? undefined : UserFromJSON(json['created_by']),
    };
}

export function PatchedRecipeImageItemToJSON(value?: Omit<PatchedRecipeImageItem, 'created_at'|'updated_at'|'created_by'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'recipe': value['recipe'],
        'image': value['image'],
        'image_url': value['imageUrl'],
        'is_primary': value['isPrimary'],
        'sort_order': value['sortOrder'],
    };
}

