/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecipeImageReorderRequest
 */
export interface RecipeImageReorderRequest {
    /**
     * 
     * @type {number}
     * @memberof RecipeImageReorderRequest
     */
    recipe: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof RecipeImageReorderRequest
     */
    order: Array<number>;
}

/**
 * Check if a given object implements the RecipeImageReorderRequest interface.
 */
export function instanceOfRecipeImageReorderRequest(value: object): value is RecipeImageReorderRequest {
    if (!('recipe' in value) || value['recipe'] === undefined) return false;
    if (!('order' in value) || value['order'] === undefined) return false;
    return true;
}

export function RecipeImageReorderRequestFromJSON(json: any): RecipeImageReorderRequest {
    return RecipeImageReorderRequestFromJSONTyped(json, false);
}

export function RecipeImageReorderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipeImageReorderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'recipe': json['recipe'],
        'order': json['order'],
    };
}

export function RecipeImageReorderRequestToJSON(value?: RecipeImageReorderRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'recipe': value['recipe'],
        'order': value['order'],
    };
}

