/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * Serializer for individual RecipeImage objects (multiple images per recipe).
 * @export
 * @interface RecipeImageItem
 */
export interface RecipeImageItem {
    /**
     * 
     * @type {number}
     * @memberof RecipeImageItem
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof RecipeImageItem
     */
    recipe: number;
    /**
     * 
     * @type {string}
     * @memberof RecipeImageItem
     */
    image?: string;
    /**
     * 
     * @type {string}
     * @memberof RecipeImageItem
     */
    imageUrl?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RecipeImageItem
     */
    isPrimary?: boolean;
    /**
     * 
     * @type {number}
     * @memberof RecipeImageItem
     */
    sortOrder?: number;
    /**
     * 
     * @type {Date}
     * @memberof RecipeImageItem
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof RecipeImageItem
     */
    readonly updatedAt: Date;
    /**
     * 
     * @type {User}
     * @memberof RecipeImageItem
     */
    readonly createdBy: User;
}

/**
 * Check if a given object implements the RecipeImageItem interface.
 */
export function instanceOfRecipeImageItem(value: object): value is RecipeImageItem {
    if (!('recipe' in value) || value['recipe'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    return true;
}

export function RecipeImageItemFromJSON(json: any): RecipeImageItem {
    return RecipeImageItemFromJSONTyped(json, false);
}

export function RecipeImageItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipeImageItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'recipe': json['recipe'],
        'image': json['image'] == null ? undefined : json['image'],
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
        'isPrimary': json['is_primary'] == null ? undefined : json['is_primary'],
        'sortOrder': json['sort_order'] == null ? undefined : json['sort_order'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'createdBy': UserFromJSON(json['created_by']),
    };
}

export function RecipeImageItemToJSON(value?: Omit<RecipeImageItem, 'created_at'|'updated_at'|'created_by'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'recipe': value['recipe'],
        'image': value['image'],
        'image_url': value['imageUrl'],
        'is_primary': value['isPrimary'],
        'sort_order': value['sortOrder'],
    };
}

