/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReorderResponse
 */
export interface ReorderResponse {
    /**
     * 
     * @type {string}
     * @memberof ReorderResponse
     */
    status: string;
}

/**
 * Check if a given object implements the ReorderResponse interface.
 */
export function instanceOfReorderResponse(value: object): value is ReorderResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ReorderResponseFromJSON(json: any): ReorderResponse {
    return ReorderResponseFromJSONTyped(json, false);
}

export function ReorderResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReorderResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function ReorderResponseToJSON(value?: ReorderResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
    };
}

